"""Small-model configuration."""

import os

from src.settings import (
    MODEL_DIRECTORY,
    SMALL_MODEL_MIN_CLUSTER_SIZE,
    SMALL_MODEL_MIN_FRAUD_COUNT,
    SMALL_MODEL_SUSPICIOUS_LOWER_BOUND,
    SMALL_MODEL_SUSPICIOUS_RATE,
    SMALL_MODEL_UNUSUAL_RATE,
    SMALL_MODEL_WINDOW_DAYS,
)

MODEL_PATH = MODEL_DIRECTORY / "small_model_current.joblib"
MAX_CLUSTERS = int(os.getenv("SMALL_MODEL_MAX_CLUSTERS", "12"))
MIN_FRAUDS_PER_CLUSTER = int(os.getenv("SMALL_MODEL_MIN_FRAUDS_PER_CLUSTER", "5"))
DISTANCE_QUANTILE = float(os.getenv("SMALL_MODEL_DISTANCE_QUANTILE", "0.95"))

__all__ = [
    "DISTANCE_QUANTILE",
    "MAX_CLUSTERS",
    "MIN_FRAUDS_PER_CLUSTER",
    "MODEL_PATH",
    "SMALL_MODEL_MIN_CLUSTER_SIZE",
    "SMALL_MODEL_MIN_FRAUD_COUNT",
    "SMALL_MODEL_SUSPICIOUS_RATE",
    "SMALL_MODEL_SUSPICIOUS_LOWER_BOUND",
    "SMALL_MODEL_UNUSUAL_RATE",
    "SMALL_MODEL_WINDOW_DAYS",
]
