"""Environment-backed application settings with conservative defaults."""

import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
MODEL_DIRECTORY = Path(os.getenv("MODEL_DIRECTORY", str(PROJECT_ROOT / "models")))

BIG_MODEL_UNUSUAL_THRESHOLD = float(os.getenv("BIG_MODEL_UNUSUAL_THRESHOLD", "0.70"))
BIG_MODEL_SUSPICIOUS_THRESHOLD = float(
    os.getenv("BIG_MODEL_SUSPICIOUS_THRESHOLD", "0.90")
)

SMALL_MODEL_UNUSUAL_RATE = float(os.getenv("SMALL_MODEL_UNUSUAL_RATE", "0.10"))
SMALL_MODEL_SUSPICIOUS_RATE = float(os.getenv("SMALL_MODEL_SUSPICIOUS_RATE", "0.30"))
SMALL_MODEL_MIN_CLUSTER_SIZE = int(os.getenv("SMALL_MODEL_MIN_CLUSTER_SIZE", "20"))
SMALL_MODEL_MIN_FRAUD_COUNT = int(os.getenv("SMALL_MODEL_MIN_FRAUD_COUNT", "3"))

RANDOM_SEED = int(os.getenv("RANDOM_SEED", "42"))

RECURRING_TRANSACTION_MINIMUM = int(os.getenv("RECURRING_TRANSACTION_MINIMUM", "5"))
RECURRING_TRANSACTION_AGE_DAYS = int(os.getenv("RECURRING_TRANSACTION_AGE_DAYS", "7"))
RECURRING_TRANSACTION_AMOUNT_VARIANCE = float(
    os.getenv("RECURRING_TRANSACTION_AMOUNT_VARIANCE", "5.0")
)
RECURRING_TRANSACTION_TIME_VARIANCE_MINUTES = int(
    os.getenv("RECURRING_TRANSACTION_TIME_VARIANCE_MINUTES", "30")
)
