"""Environment-backed application settings with conservative defaults."""

import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
MODEL_DIRECTORY = Path(os.getenv("MODEL_DIRECTORY", str(PROJECT_ROOT / "models")))

BIG_MODEL_UNUSUAL_THRESHOLD = float(os.getenv("BIG_MODEL_UNUSUAL_THRESHOLD", "0.70"))
BIG_MODEL_SUSPICIOUS_THRESHOLD = float(
    os.getenv("BIG_MODEL_SUSPICIOUS_THRESHOLD", "0.90")
)

SMALL_MODEL_UNUSUAL_RATE = float(os.getenv("SMALL_MODEL_UNUSUAL_RATE", "0.05"))
SMALL_MODEL_SUSPICIOUS_RATE = float(os.getenv("SMALL_MODEL_SUSPICIOUS_RATE", "0.10"))
SMALL_MODEL_SUSPICIOUS_LOWER_BOUND = float(
    os.getenv("SMALL_MODEL_SUSPICIOUS_LOWER_BOUND", "0.08")
)
SMALL_MODEL_MIN_CLUSTER_SIZE = int(os.getenv("SMALL_MODEL_MIN_CLUSTER_SIZE", "100"))
SMALL_MODEL_MIN_FRAUD_COUNT = int(os.getenv("SMALL_MODEL_MIN_FRAUD_COUNT", "20"))

RANDOM_SEED = int(os.getenv("RANDOM_SEED", "42"))

IMPOSSIBLE_TRAVEL_THRESHOLD_KMH = float(
    os.getenv("IMPOSSIBLE_TRAVEL_THRESHOLD_KMH", "500.0")
)
NEW_PAYEE_ALERT_THRESHOLD = float(os.getenv("NEW_PAYEE_ALERT_THRESHOLD", "10000.0"))
FRESH_ACCOUNT_TRANSACTION_THRESHOLD = int(
    os.getenv("FRESH_ACCOUNT_TRANSACTION_THRESHOLD", "5")
)
FRESH_ACCOUNT_AGE_DAYS = int(os.getenv("FRESH_ACCOUNT_AGE_DAYS", "15"))

RECURRING_TRANSACTION_MINIMUM = int(os.getenv("RECURRING_TRANSACTION_MINIMUM", "5"))
RECURRING_TRANSACTION_AGE_DAYS = int(os.getenv("RECURRING_TRANSACTION_AGE_DAYS", "7"))
RECURRING_TRANSACTION_AMOUNT_VARIANCE = float(
    os.getenv("RECURRING_TRANSACTION_AMOUNT_VARIANCE", "5.0")
)
RECURRING_TRANSACTION_TIME_VARIANCE_MINUTES = int(
    os.getenv("RECURRING_TRANSACTION_TIME_VARIANCE_MINUTES", "30")
)

SMALL_MODEL_WINDOW_DAYS = int(os.getenv("SMALL_MODEL_WINDOW_DAYS", "60"))
